// const errCheck = async (req, res, next) => {
//     server.on('error', (err) => {
//         console.error('Server encountered an error:', err);
//         // Dừng server
//         server.close(() => {
//             console.log('Restarting server...');
//             // Chờ một chút rồi khởi động lại
//             setTimeout(startServer, 5000);
//         });
//     });
// }
// module.exports = errCheck;
